# Generated by Django 3.0 on 2019-12-14 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gameViewer', '0003_auto_20191214_0623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='picture',
            field=models.ImageField(upload_to='game_cover_art/'),
        ),
    ]
